export type ShopCategory = "Frames" | "Banners" | "Titles" | "Effects" | "Themes";

export type ShopItemRarity = "common" | "rare" | "epic";

export type ShopItem = {
  id: string;
  category: ShopCategory;
  name: string;
  description: string;
  rarity: ShopItemRarity;
  price: number;
  owned: boolean;
  equipped: boolean;
  accent: "silver" | "amber" | "blue" | "green" | "red" | "white";
};

export const SHOP_CATEGORIES: readonly ShopCategory[] = [
  "Frames",
  "Banners",
  "Titles",
  "Effects",
  "Themes",
];

export const MOCK_SHOP_ITEMS: readonly ShopItem[] = [
  {
    id: "oblivion",
    category: "Frames",
    name: "Oblivion",
    description: "A minimal frame for those who build in the quiet.",
    rarity: "common",
    price: 0,
    owned: true,
    equipped: true,
    accent: "silver",
  },
  {
    id: "solar-flare",
    category: "Frames",
    name: "Solar Flare",
    description: "Brighten the edge of your developer identity.",
    rarity: "rare",
    price: 500,
    owned: false,
    equipped: false,
    accent: "amber",
  },
  {
    id: "fracture",
    category: "Frames",
    name: "Fracture",
    description: "A sharper silhouette for high-visibility builds.",
    rarity: "rare",
    price: 500,
    owned: false,
    equipped: false,
    accent: "blue",
  },
  {
    id: "verdant",
    category: "Frames",
    name: "Verdant",
    description: "Quiet green momentum for the steady shipper.",
    rarity: "common",
    price: 750,
    owned: false,
    equipped: false,
    accent: "green",
  },
  {
    id: "crimson-arc",
    category: "Frames",
    name: "Crimson Arc",
    description: "A strong signal of relentless delivery.",
    rarity: "rare",
    price: 750,
    owned: false,
    equipped: false,
    accent: "red",
  },
  {
    id: "eclipse",
    category: "Frames",
    name: "Eclipse",
    description: "A dark, controlled frame tuned for depth.",
    rarity: "epic",
    price: 1000,
    owned: false,
    equipped: false,
    accent: "white",
  },
  {
    id: "night-canopy",
    category: "Banners",
    name: "Night Canopy",
    description: "A quiet horizon for a profile shaped by patient work.",
    rarity: "common",
    price: 300,
    owned: false,
    equipped: false,
    accent: "blue",
  },
  {
    id: "emberline",
    category: "Banners",
    name: "Emberline",
    description: "A measured streak of warmth across the dark.",
    rarity: "rare",
    price: 600,
    owned: false,
    equipped: false,
    accent: "amber",
  },
  {
    id: "the-builder",
    category: "Titles",
    name: "The Builder",
    description: "For the ones who turn a blank page into working things.",
    rarity: "common",
    price: 250,
    owned: true,
    equipped: true,
    accent: "silver",
  },
  {
    id: "systems-thinker",
    category: "Titles",
    name: "Systems Thinker",
    description: "A title for seeing how every piece fits together.",
    rarity: "epic",
    price: 850,
    owned: false,
    equipped: false,
    accent: "blue",
  },
  {
    id: "signal-trace",
    category: "Effects",
    name: "Signal Trace",
    description: "A restrained signal line to mark your profile presence.",
    rarity: "rare",
    price: 500,
    owned: false,
    equipped: false,
    accent: "green",
  },
  {
    id: "quiet-pulse",
    category: "Effects",
    name: "Quiet Pulse",
    description: "A soft pulse that keeps the focus on your work.",
    rarity: "epic",
    price: 900,
    owned: false,
    equipped: false,
    accent: "red",
  },
  {
    id: "graphite",
    category: "Themes",
    name: "Graphite",
    description: "A deep neutral palette with crisp, understated contrast.",
    rarity: "common",
    price: 0,
    owned: true,
    equipped: true,
    accent: "silver",
  },
  {
    id: "deep-current",
    category: "Themes",
    name: "Deep Current",
    description: "Cool blue details over RootRealm's familiar dark canvas.",
    rarity: "rare",
    price: 700,
    owned: false,
    equipped: false,
    accent: "blue",
  },
];
